language: java
install:
- mvn install
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: nvQt4gbm0DNDsi9BrlAfSSiHMOVwDHDc/m4TL5ASsFpJ6an979xuAPbTyMhSLZNcBQHavYwXx+za/omWXmPvRIOUK/26Wi+ynB5Y1npg3PHtSjwAYVQGuO0qd6V8XtP9G2BFqFYP25T7FASX7LJ9hjRv9kR5PAaTl2jUocyuR1KZObH7l9Jy0j+EnsYzp3LpkBRnZzDhFcp544npYXuzsEgeG7700Qyg1xl1xjrcanq9utT4Eg9DjUrqiHGgfKTVz3ysgtududVDELLobwDJnZqwKwVBNTxKy3muAp5/8sOqduFmiIV1t8SITqxm4NG1MOq6WVyPTsi9ffFxPRcQRlnWtQE0XrS4alOZVkxfVf0UeWko6UCTLQc1KCPE3IgYfzFRrnLAqzulu2B6WpVeBHoP/ZQn3Wxz3iTOekIZyaGergWKkiWYuzkXbLNROkRia42zVZ/L8czeFmXJdSCCPbNaGczoLMKB7sIZG2VWycgpv8BfmXBNfznNsPIOnGsHXDf4KqaTdJpABDhbnsU5YVfSDCr13thRxsoZe3DLDHJpy5Sf3t2d9c1CCbwJJC4WuX81lb8SutXiusLjKv513HGe4oKBsIXNsEtIHadlnDuzUvxKhNKOE0Di8eCLF/P+TPhVJFITmfNsmyqHP6fQL4Kzyiw3EEgzlRNtuHbziOU=
  app: egetumer-addressbook
  on:
    repo: egetumer/addressbook
    branch: todo_tasks
