language: java
install:
- mvn install
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api_key: 14678da7-9359-4f94-93e7-65717173f62c
  app: egetumer-addressbook
  on:
    repo: egetumer/addressbook
    branch: todo_tasks
