language: java
install:
- mvn install
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: qLCOLRwkYzHTzC641C9CdgbdjXuntQvwCcNfOZ1YQaGDuQaQ8KMI/YEIXectWikDa6N6TnxKT1szIuvKV+gGcnkkFo7xDHsyxR2giHMrs/V1bUXbTzjErrH1ZjNZXlwwCa0e2+jSWSKBXisFOt2LUve58COi/PfbUtlrjXv8CPgmgstjnXkB9H7xAe5ZB1q9/U9TYCXMCy1v6xmALjQjjAhBa/KSjADBVRCAzpi7JX4B273Ti9OTxwB5XQJ4p18WfdFdoiGh/zuMZIfHMfId43/Cvf2Y/q8qSN0+HBBx5CryPI/1IetNTeXOxSjPTVOOA1xQ7IpWPT9eD/kc8T0EGmtzXTq6Cr52t0U58JYVr+pjwJF7hBgigtkNDdvgJXvqjvgb9xLQwRz8zNyrNrF/rOWTyy5XCmgPIIp30uIsOksP8t/PieplunK9XGDyNZ3FRrXcHnTgAAXmI+aIHKjP91h1QQmSPDrqHwXv6Chvrg+3/9C40e8lv06/I0K04dHjzjhp+liMR/4E1iwOWLFv1vleVd523tPf5vk5URRmQDormB8wUZdrjyGYITsnd+G05Un1UvxkXYc68XkYtQdUeyA0C5va1tQMs0UMzxdGbp6ZdbLnRoCkGKkxVN3Itk18cL2h7UgctuCA73t5XLz+018pE9g8DD4hKeu6ZTZ+FP8=
  app: egetumer-addressbook
  on:
    repo: egetumer/addressbook
    branch: todo_tasks
